// Dữ liệu sản phẩm - Được tạo tự động bởi product_manager.py
const productsData = [
    {
        "id": "may_chieu_mini_di_dong_goojodoq",
        "name": "Máy chiếu Mini di động GOOJODOQ",
        "image": "../aff-data/may_chieu_mini_di_dong_goojodoq.webp",
        "qrImage": "../aff-data/may_chieu_mini_di_dong_goojodoq_qr.webp",
        "priceNow": "1.143.120₫",
        "priceOriginal": "2.980.000₫",
        "discount": "-62%",
        "buyLink": "https://s.shopee.vn/10vZa6Mqmk",
        "description": [
            "Chân đế cao và góc tự do 270°: Chân đế máy chiếu thông minh tất cả trong một này có thiết kế chân đế với hướng chiếu xoay 270°, cho phép bạn tự do chiếu hình ảnh từ các góc khác nhau lên tường hoặc trần nhà. Bạn có thể hướng máy chiếu lên trần phòng ngủ và thưởng thức phim khi nằm trên giường.",
            "Bluetooth 2.4 và 5G Wi-Fi: Wi-Fi 2.4G + 5G băng tần kép mới nhất (hỗ trợ Wi-Fi6) được thiết kế để giảm độ trễ phát trực tuyến/chơi game trực tuyến và mang lại hình ảnh mượt mà Chip Bluetooth 5.0 giúp đồng bộ hóa âm thanh nhanh hơn và hiệu quả hơn Trơn tru. Ổn định và cải thiện trải nghiệm xem của bạn.",
            "Hệ điều hành Android 11 đa năng: Hệ điều hành Android 11 tích hợp cho phép bạn dễ dàng truy cập nhiều ứng dụng hoặc trang web trực tuyến khác nhau mà không cần thêm thiết bị. Bạn có thể tải xuống nhiều ứng dụng, chơi trò chơi, chia sẻ ảnh/video/tài liệu, xem phim và lướt Internet giống như sử dụng điện thoại di động, điều này sẽ nâng cao trải nghiệm xem của bạn.",
            "Hình ảnh rõ ràng và đầy màu sắc: Độ phân giải gốc 720p giải mã độ phân giải 4K, có độ sáng 160ANSI, chiếu hình ảnh rõ hơn, sáng hơn và phong phú hơn và có thể đạt được hiệu ứng trình chiếu tuyệt vời ngay cả vào ban ngày, xử lý chi tiết hiệu quả và giữ nguyên chất lượng hình ảnh gốc, Thích hợp cho rạp hát tại nhà , tài liệu văn phòng và đào tạo kinh doanh.",
            "Tự động chỉnh sửa keystone: Máy chiếu thông minh của chúng tôi sử dụng tính năng chỉnh sửa keystone tự động thông qua điều khiển từ xa để mang đến cho bạn hình ảnh hoàn hảo. Hình ảnh chiếu có thể được chỉnh sửa nhanh chóng và luôn xuất hiện ở đúng vị trí.",
            "Thưởng thức hình ảnh lớn 130 inch: Máy chiếu di động này có màn hình 40-130 inch, vì vậy bạn có thể chọn kích thước màn hình phù hợp theo nhu cầu của mình và tạo ra một đêm chơi game hoặc phim thú vị. Kích thước chiếu tối đa là 130 inch, đảm bảo màn hình lớn và mang lại trải nghiệm xem sống động, giống như xem phim trong rạp chiếu phim.",
            "Máy chiếu cầm tay mini: Máy chiếu mini nhỏ gọn và phù hợp để sử dụng bằng một tay. Với trọng lượng khoảng 0,5 kg, bạn có thể dễ dàng mang theo bên mình. Với chân đế thông minh, bạn có thể thưởng thức phim, video và trò chơi tại nhà hoặc khi ở ngoài trời, đi du lịch hoặc cắm trại."
        ]
    },
    {
        "id": "man_hinh_cong_spin_24_27_32_full_hd_2k",
        "name": "Màn hình cong Spin 24/27/32\" Full HD/2K",
        "image": "../aff-data/man_hinh_cong_spin_24_27_32_full_hd_2k.jpg",
        "qrImage": "../aff-data/man_hinh_cong_spin_24_27_32_full_hd_2k_qr.webp",
        "priceNow": "1.735.000₫",
        "priceOriginal": "2.350.000₫",
        "discount": "-26%",
        "buyLink": "https://s.shopee.vn/5fhOKWcNSH",
        "description": [
            "PANEL TYPE: VA",
            "SCREEN SIZE: 27\"",
            "RESOLUTION: 1920×1080",
            "FULL HD",
            "BACKLIGHT: LED",
            "RESPONSE TIME: 2ms",
            "BRIGHTNESS: 200 cd/m²",
            "REFRESH RATE: 100Hz",
            "CONTRAST RATIO: 1000:1",
            "Sản phẩm Spin được bảo hành 12 tháng (tuỳ dòng sản phẩm) cho các lỗi từ nhà sản xuất.",
            "Bảo hành không áp dụng khi sản phẩm hết hạn, serial/IMEI/tem bảo hành không đọc được, bị tháo hoặc làm giả.",
            "Không áp dụng cho hư hỏng do sửa chữa trái phép, sử dụng sai cách, va đập, chất lỏng, tai nạn, thay đổi hoặc lắp đặt sai quy định.",
            "Không bảo hành phụ kiện, bao bì, quà tặng, hướng dẫn sử dụng, hóa đơn/biên lai bị mất hoặc sửa đổi.",
            "Không áp dụng cho hư hỏng do bất khả kháng.",
            "Không bảo hành nếu thiết bị mua theo đơn/hóa đơn không trùng khớp với thiết bị gửi bảo hành.",
            "Không áp dụng cho các hư hỏng phát sinh do sử dụng sai mục đích hoặc môi trường không phù hợp hướng dẫn sử dụng."
        ]
    },
    {
        "id": "loa_bluetooth_soundbar_led_dopetech_a39",
        "name": "Loa Bluetooth Soundbar LED DOPETECH A39",
        "image": "../aff-data/loa_bluetooth_soundbar_led_dopetech_a39.webp",
        "qrImage": "../aff-data/loa_bluetooth_soundbar_led_dopetech_a39_qr.webp",
        "priceNow": "207.000₫",
        "priceOriginal": "280.000₫",
        "discount": "-25%",
        "buyLink": "https://s.shopee.vn/8AOjKEaFoe",
        "description": [
            "THÔNG SỐ KỸ THUẬT",
            "Kích thước: 35 × 7 × 7 cm",
            "Điện trở: 4Ω",
            "Công suất: 3W × 2",
            "Tần số: 100Hz – 20KHz",
            "S/N: ≥ 70dB",
            "Nguồn: USB 5V, âm thanh qua jack 3.5mm",
            "Tương thích: PC, laptop, điện thoại có cổng 3.5mm",
            "HƯỚNG DẪN LẮP ĐẶT",
            "Loa có 1 chân USB và 1 jack 3.5mm",
            "B1: Cắm USB để cấp điện cho loa",
            "B2: Cắm jack 3.5mm vào cổng tai nghe trên PC, laptop hoặc điện thoại",
            "B3: Bật nhạc và chỉnh âm lượng ở thiết bị và trên loa",
            "LƯU Ý",
            "Phải cắm đồng thời USB và jack 3.5mm mới sử dụng được",
            "TÍNH NĂNG NỔI BẬT",
            "Thiết kế mini nhỏ gọn, phù hợp không gian bàn làm việc",
            "Âm thanh phù hợp kích thước, bass rõ, nghe ổn định",
            "Trang bị LED dạ quang nổi bật, tăng điểm nhấn cho góc học tập và làm việc",
            "Sử dụng nguồn USB tiện lợi cho mọi thiết bị",
            "Điều chỉnh âm lượng dễ dàng, âm thanh trong – bass trầm nghe thoải mái",
            "Có công tắc bật tắt nguồn và LED",
            "BẢO HÀNH – ĐỔI TRẢ",
            "Hỗ trợ 1 đổi 1 trong 24 giờ",
            "Bảo hành 6 tháng"
        ]
    },
    {
        "id": "ban_phim_gaming_co_day_sidotech_ldk_v4_pro",
        "name": "Bàn phím gaming có dây SIDOTECH LDK V4 Pro",
        "image": "../aff-data/ban_phim_gaming_co_day_sidotech_ldk_v4_pro.webp",
        "qrImage": "../aff-data/ban_phim_gaming_co_day_sidotech_ldk_v4_pro_qr.webp",
        "priceNow": "133.999₫",
        "priceOriginal": "199.000₫",
        "discount": "-33%",
        "buyLink": "https://s.shopee.vn/9pWxIPpiKB",
        "description": [
            "PHIÊN BẢN: V5 PRO – V4 PRO – V4",
            "CHẤT LIỆU: V5 PRO nhựa ABS cao cấp – V4 PRO đế kim loại – V4 nhựa ABS thường",
            "TUỔI THỌ: V5 PRO 15 triệu lượt nhấn – V4 PRO 10 triệu lượt nhấn – V4 10 triệu lượt nhấn",
            "TỐC ĐỘ PHẢN HỒI: V5 PRO ≈1ms – V4 PRO ≈1.5ms – V4 ≈2ms",
            "ĐÈN LED: Cả 3 phiên bản dùng LED rainbow",
            "CHỐNG NƯỚC: V5 PRO cực tốt – V4 PRO cực tốt – V4 tốt",
            "Tên sản phẩm V5 PRO – kích thước 485×185×45mm – trọng lượng 980g – full size 104 phím",
            "Tên sản phẩm V4 PRO – kích thước 458×178×28mm – trọng lượng 890g – full size 104 phím",
            "Tên sản phẩm V4 – kích thước 434×136×33mm – trọng lượng 520g – full size 104 phím",
            "Kết nối có dây trên cả 3 phiên bản",
            "Chuẩn chống nước: V5 PRO IP68 – V4 PRO IP68 – V4 IP67",
            "Loại phím: Giả cơ trên cả 3 phiên bản",
            "Tương thích: Win7/8/10/11 – IOS – XP – VISTA",
            "CHÍNH SÁCH ĐỔI TRẢ: Áp dụng khi hàng lỗi kỹ thuật, hư hỏng do vận chuyển, giao sai mẫu hoặc thiếu phụ kiện",
            "ĐIỀU KIỆN ĐỔI TRẢ: Báo lỗi trong 7 ngày; cung cấp video mở hộp; sản phẩm còn đầy đủ phụ kiện",
            "KHÔNG ĐỦ ĐIỀU KIỆN ĐỔI TRẢ: Hư hỏng do người dùng; không có video chứng minh; thiếu phụ kiện khi hoàn về",
            "ĐIỀU KIỆN BẢO HÀNH: Lỗi kỹ thuật do nhà sản xuất; đã kích hoạt bảo hành online; còn thời hạn bảo hành",
            "HÌNH THỨC ĐỔI TRẢ: Sidotech đổi sản phẩm mới 100% nếu đủ điều kiện",
            "CHI PHÍ ĐỔI TRẢ: Miễn phí vận chuyển nếu xác định lỗi từ Sidotech",
            "HÌNH THỨC BẢO HÀNH: Sidotech sửa chữa hoặc đổi mới 100% tùy mức độ hư hỏng"
        ]
    },
    {
        "id": "chuot_gaming_sidotech_inphic_p1w",
        "name": "Chuột gaming SIDOTECH Inphic P1W",
        "image": "../aff-data/chuot_gaming_sidotech_inphic_p1w.webp",
        "qrImage": "../aff-data/chuot_gaming_sidotech_inphic_p1w_qr.webp",
        "priceNow": "107.000₫",
        "priceOriginal": "189.000₫",
        "discount": "-43%",
        "buyLink": "https://s.shopee.vn/6fZvWzs0wc",
        "description": [
            "Tên sản phẩm: P1W",
            "Kích thước: 120 × 78 × 38 mm",
            "Trọng lượng: 95 ± 5 g",
            "Kết nối: Có dây",
            "Điện áp: 5V / 100mA",
            "Chiều dài dây: 1.5 m",
            "Độ nhạy DPI: 800 / 1200 / 7200 DPI",
            "Tương thích: Win7 / Win8 / Win10 / Win11 / IOS / XP / VISTA",
            "Tuổi thọ 40 triệu click sử dụng bền bỉ đến 5 năm",
            "Độ nhạy 7200 DPI phản hồi nhanh và chính xác",
            "Thiết kế công thái học cho cảm giác cầm chắc và thoải mái",
            "Công nghệ click tắt tiếng (silent) phù hợp chơi game ban đêm và môi trường văn phòng",
            "Bề mặt nhựa nhám cao cấp chống trơn trượt và chống bám mồ hôi",
            "Chuột có dây P1W sử dụng công nghệ HUANO cho độ chính xác cao và tuổi thọ lớn",
            "Sản phẩm có 6 phiên bản DPI/kiểu kết nối theo ảnh so sánh",
            "Thiết kế công thái học giúp ôm tay và tạo sự thoải mái khi sử dụng lâu",
            "Chuột silent giảm tiếng ồn khi click, phù hợp môi trường yên tĩnh",
            "DPI là chỉ số độ nhạy, DPI càng cao tốc độ di chuyển càng nhanh và mượt",
            "Cảm biến quang học độ nhạy cao giúp thao tác chuẩn xác khi chơi game",
            "P1W dùng switch HUANO tăng tốc độ phản hồi và độ bền lên đến 30 triệu lần nhấn",
            "Con lăn nâng cấp cho thao tác cuộn chính xác và mượt hơn",
            "Trang bị 4 miếng đế chống trượt giúp chuột bám tốt trên mọi bề mặt",
            "Chính sách đổi trả khi hàng lỗi kỹ thuật từ nhà sản xuất",
            "Đổi trả nếu hàng bị hư hỏng do vận chuyển hoặc giao sai mẫu, thiếu phụ kiện",
            "Khách phải báo lỗi trong 7 ngày tính từ lúc nhận hàng",
            "Bắt buộc cung cấp video mở hộp để xác minh lỗi",
            "Sản phẩm gửi đổi trả phải còn đầy đủ phụ kiện",
            "Không đủ điều kiện đổi trả nếu sản phẩm hư do lỗi người dùng",
            "Không đổi trả nếu không có video/hình ảnh chứng minh lỗi",
            "Không đổi trả khi thiếu phụ kiện ban đầu",
            "Bảo hành khi sản phẩm lỗi kỹ thuật do nhà sản xuất",
            "Bảo hành yêu cầu kích hoạt online từ thẻ bảo hành",
            "Sản phẩm phải còn trong thời hạn bảo hành",
            "Sidotech đổi mới 100% nếu đủ điều kiện lỗi",
            "Miễn phí vận chuyển nếu xác định lỗi thuộc Sidotech"
        ]
    },
    {
        "id": "tai_nghe_bluetooth_5_3_goojodoq_j201",
        "name": "Tai nghe Bluetooth 5.3 GOOJODOQ J201",
        "image": "../aff-data/tai_nghe_bluetooth_5_3_goojodoq_j201.webp",
        "qrImage": "../aff-data/tai_nghe_bluetooth_5_3_goojodoq_j201_qr.webp",
        "priceNow": "136.220₫",
        "priceOriginal": "180.000₫",
        "discount": "-24%",
        "buyLink": "https://s.shopee.vn/2qNCyAWUve",
        "description": [
            "Phiên bản Bluetooth: 5.3",
            "Dung lượng pin tai nghe: 45mAh",
            "Dung lượng pin hộp sạc: 200mAh (có bảng bảo vệ pin)",
            "Khoảng cách kết nối: 10 mét",
            "Thời gian sạc: 1 giờ",
            "Thời gian chờ: 60 giờ",
            "Tính năng 1 chạm trả lời và gọi lại",
            "Phát / tạm dừng nhạc trực tiếp trên tai nghe",
            "Cuộc gọi song phương và tự động ghép nối",
            "Âm thanh stereo với loa F13",
            "Cổng sạc Type-C, có lỗ treo tránh thất lạc",
            "Thiết kế độc quyền được cấp bằng sáng chế",
            "Thời lượng pin dài với hộp sạc 200mAh",
            "Thời gian thoại lên đến 8 giờ",
            "Hỗ trợ dịch AI thông qua app Dana ID",
            "Dịch trực tiếp / dịch văn bản trong 36 ngôn ngữ",
            "Trợ lý hội thoại AI – hỗ trợ tiếng Anh",
            "Phiên âm AI – tốc ký cuộc họp",
            "Tìm kiếm AI toàn web và tóm tắt nội dung",
            "Phù hợp họp kinh doanh đa ngôn ngữ và du lịch quốc tế",
            "Tai nghe Bluetooth 5.3 kết nối ổn định và xa hơn 15 mét",
            "Tốc độ truyền nhanh và tiết kiệm năng lượng",
            "Hỗ trợ điều khiển cảm ứng tiện lợi",
            "Trình điều khiển 13.2mm cho âm trầm sâu và âm cao rõ ràng",
            "Âm thanh trong trẻo và sống động",
            "Công nghệ ENC giảm tiếng ồn môi trường khi gọi",
            "Giữ giọng nói rõ ngay cả nơi ồn ào",
            "Pin tai nghe 35mAh, pin hộp sạc 250mAh",
            "Thời gian nghe 3.5 – 4 giờ mỗi lần sạc",
            "Thời gian chờ hộp sạc lên đến 120 giờ",
            "Thiết kế nhỏ gọn, có dây buộc tiện mang theo",
            "Nhét túi hoặc treo balo dễ dàng",
            "Chống nước IPX4, không cần tháo khi tập luyện",
            "Thiết kế đeo thoải mái lâu dài, giảm đau tai"
        ]
    },
    {
        "id": "den_led_cam_ung_dieu_sang_onr",
        "name": "Đèn LED cảm ứng điều sáng ONR",
        "image": "../aff-data/den_led_cam_ung_dieu_sang_onr.webp",
        "qrImage": "../aff-data/den_led_cam_ung_dieu_sang_onr_qr.webp",
        "priceNow": "79.000₫",
        "priceOriginal": "99.000₫",
        "discount": "-20%",
        "buyLink": "https://s.shopee.vn/40ZB9kLsWQ",
        "description": [
            "Tên sản phẩm: Đèn LED cảm ứng ONR",
            "Chức năng: đèn trang trí, đèn cảm biến, đèn ngủ, đèn chiếu sáng xung quanh",
            "Điện áp: 36V",
            "Chất liệu chao đèn: PVC",
            "Loại công tắc: cảm ứng",
            "Phong cách: hiện đại, đơn giản",
            "Tuổi thọ trung bình: 10.000 giờ",
            "Dịp tặng quà phù hợp: sinh nhật, tân gia, lễ hội, quà doanh nghiệp, sự kiện, phúc lợi nhân viên",
            "Kích thước: 20cm / 40cm / 50cm / 60cm",
            "Màu sắc: đen",
            "Công suất: 1–6W",
            "Nguồn điện: pin tích hợp sạc lại",
            "Cách hoạt động:",
            "Nhấn 1 lần: bật chế độ luôn sáng",
            "Nhấn 2 lần: bật cảm biến ban đêm",
            "Nhấn 3 lần: bật cảm biến cả ngày",
            "Nhấn 4 lần: tắt",
            "Cổng sạc: Type-C",
            "Thay đổi ánh sáng bằng 3 lần nhấn: ánh sáng ấm / trung tính / trắng",
            "Độ sáng có thể điều chỉnh",
            "Bộ sản phẩm gồm: 1 đèn LED cảm ứng ONR",
            "Lưu ý màu sắc có thể chênh lệch do ánh sáng và màn hình",
            "Kích thước có thể sai lệch nhỏ do đo thủ công",
            "Hàng luôn sẵn kho, giao nhanh",
            "Liên hệ CSKH khi cần hỗ trợ",
            "Hạn chế đánh giá tiêu cực vì cửa hàng luôn sẵn sàng xử lý",
            "Rất mong nhận được đánh giá 5 sao để cải thiện dịch vụ"
        ]
    },
    {
        "id": "den_hoc_kep_ban_oem_chong_can",
        "name": "Đèn học kẹp bàn OEM chống cận",
        "image": "../aff-data/den_hoc_kep_ban_oem_chong_can.webp",
        "qrImage": "../aff-data/den_hoc_kep_ban_oem_chong_can_qr.webp",
        "priceNow": "151.999₫",
        "priceOriginal": "300.000₫",
        "discount": "-49%",
        "buyLink": "https://s.shopee.vn/7V97AjqR1n",
        "description": [
            "Đèn học kẹp bàn chống cận LED bảo vệ mắt",
            "Thiết kế kẹp bàn chắc chắn, tiết kiệm không gian",
            "Ba chế độ ánh sáng: trắng – vàng – trung tính",
            "Ánh sáng dịu, không nhấp nháy, không chói, giảm mỏi mắt",
            "Thân đèn xoay – uốn linh hoạt nhiều góc chiếu",
            "LED tiết kiệm điện, tuổi thọ cao, ánh sáng ổn định",
            "Chất liệu hợp kim + nhựa ABS bền và sang trọng",
            "Phù hợp học sinh – sinh viên – văn phòng – đọc sách",
            "Dùng cho bàn học, đầu giường, kệ sách, bàn trang điểm",
            "Nguồn điện USB 5V tiện lợi",
            "Công suất thấp, hiệu năng tốt",
            "Thiết kế nhỏ gọn, dễ tháo lắp và mang theo",
            "Ứng dụng đa năng: học tập, làm việc, thư giãn",
            "Hàng mới 100%, đúng mô tả",
            "Hỗ trợ đổi trả khi có lỗi nhà sản xuất",
            "Giao hàng nhanh, đóng gói an toàn"
        ]
    },
    {
        "id": "ke_de_man_hinh_may_tinh_led_topv",
        "name": "Kệ để màn hình máy tính LED TOPV",
        "image": "../aff-data/ke_de_man_hinh_may_tinh_led_topv.webp",
        "qrImage": "../aff-data/ke_de_man_hinh_may_tinh_led_topv_qr.webp",
        "priceNow": "81.000₫",
        "priceOriginal": "130.000₫",
        "discount": "-38%",
        "buyLink": "https://s.shopee.vn/9Uu6vYIEXL",
        "description": [
            "Kích thước kệ: dài 80/120cm – rộng 20cm – cao 11cm",
            "Kệ máy tính tích hợp sạc điện thoại dây và không dây (tùy phân loại)",
            "Tích hợp ổ cắm điện tiện lợi",
            "Có đèn LED trang trí",
            "Có đầu chia cổng USB mở rộng",
            "Có loa Bluetooth (tùy phân loại)",
            "USB trên kệ chỉ truyền tiếp từ máy tính, tốc độ sạc không nhanh bằng củ sạc",
            "Giúp thao tác ngay trên mặt bàn, không cần cúi xuống gầm bàn",
            "Kệ giúp sắp xếp đồ dùng gọn gàng, khoa học",
            "Giúp nâng màn hình, cải thiện tư thế cổ – vai – gáy",
            "Khoang dưới kệ chứa được bàn phím, chuột và đồ dùng",
            "Sản xuất bằng công nghệ CNC độ chính xác 0.1mm",
            "Thiết kế giấu đinh vít, thẩm mỹ và sang trọng",
            "Chất liệu MDF Malaysia phủ melamine chống ẩm mốc, chống mối mọt",
            "Độ dày gỗ 1.6cm, cứng cáp hơn sản phẩm mỏng 1–1.2cm trên thị trường",
            "Bộ sản phẩm gồm mặt kệ, chân kệ, ốc vít và hướng dẫn lắp ráp",
            "Thời gian lắp ráp chỉ 1–2 phút",
            "Bảo hành 12 tháng, 1 đổi 1 miễn phí khi lỗi từ nhà sản xuất",
            "Chiều dài dây điện khoảng 1.3m",
            "Chiều dài dây USB và sạc không dây khoảng 95cm",
            "Đèn LED màu xanh, có thể tăng giảm độ sáng"
        ]
    },
    {
        "id": "den_led_man_hinh_ambilight_skydimo",
        "name": "Đèn LED màn hình Ambilight Skydimo",
        "image": "../aff-data/den_led_man_hinh_ambilight_skydimo.webp",
        "qrImage": "../aff-data/den_led_man_hinh_ambilight_skydimo_qr.webp",
        "priceNow": "214.830₫",
        "priceOriginal": "279.000₫",
        "discount": "-23%",
        "buyLink": "https://s.shopee.vn/3fwKl5JCfC",
        "description": [
            "Đèn LED màn hình Ambilight Skydimo ’nd – phiên bản Next Design của Rainbow Music Led Việt Nam",
            "LED theo màu màn hình, hiệu ứng mở rộng mượt 60FPS",
            "Chức năng: theo màu màn hình, nháy theo nhạc, màu đơn, hiệu ứng",
            "Tương thích SignalRGB từ 10/10/2025 để đồng bộ PC – chuột – bàn phím – fan – RAM",
            "Hướng dẫn sử dụng: tìm “Rainbow Music Led huong dan”",
            "Bảo hành 1 năm – 1 đổi 1 trong 1 tháng",
            "Hỗ trợ Win7 – Win10/11 – Mac Intel/M1–M4",
            "Phần mềm cực nhẹ, dưới 0.9% CPU, không lag chuột hay game",
            "Hỗ trợ nhiều bộ LED cùng lúc, tối đa theo màu 5 màn hình",
            "Rainbow Music Led App nhẹ – mượt – nhiều tính năng",
            "Không dùng phần mềm mã nguồn mở do dễ lỗi và fps thấp",
            "Không dùng phần mềm Skydimo/Ustyle của TQ do nguy cơ theo dõi và ít hiệu ứng",
            "Tính năng chuyên nghiệp: hỗ trợ tiếng Việt/Anh",
            "Xử lý màu mượt 60FPS, độ sáng vừa phải",
            "Cắm USB là chạy ngay, không cần thiết lập",
            "Tự động kết nối lại LED khi cắm vào",
            "Tự nhận dạng bộ LED màn bao in",
            "Làm mịn ánh sáng, giảm sốc sáng tối",
            "Hòa trộn màu liền mạch",
            "Tự loại bỏ vệt đen khi xem phim lệch khung",
            "Nháy theo nhạc: 100 hiệu ứng, chuẩn – mượt – đẹp",
            "Hỗ trợ tự tạo hiệu ứng nhạc",
            "Tự tìm soundcard, không cần cài đặt",
            "Có 40 hiệu ứng màu",
            "Hỗ trợ màu đơn: xanh, đỏ, tím, vàng…",
            "Có sao lưu và phục hồi cấu hình",
            "Tự gỡ bản phần mềm cũ trước khi cài bản mới",
            "Bộ sản phẩm có 2 phiên bản (chức năng như nhau)",
            "Bản LED silicon: controller USB, cáp data 1m, cáp nguồn 1m, LED silicon uốn 90°, gá silicon + keo siêu dính",
            "Bản LED không silicon: controller USB, cáp data 1m, cáp nguồn 1m, LED ARGB 60led/m uốn 90°, kèm keo 2 mặt",
            "Khoảng cách tối đa LED đến cổng USB: 1.8m",
            "Dùng laptop nên chọn Ambilight Skydimo ’nd WiFi để linh hoạt",
            "Win7 và MacOS12 dùng phần mềm riêng, chỉ hỗ trợ một số chức năng cơ bản"
        ]
    },
    {
        "id": "combo_bap_rang_youus_netflix",
        "name": "Combo Bắp Rang Youus Netflix",
        "image": "../aff-data/combo_bap_rang_youus_netflix.webp",
        "qrImage": "../aff-data/combo_bap_rang_youus_netflix_qr.webp",
        "priceNow": "190.000₫",
        "priceOriginal": "276.700₫",
        "discount": "-31%",
        "buyLink": "https://s.shopee.vn/1LYTrZHFla",
        "description": [
            "YOUUS là một thương hiệu sản phẩm đến từ Hàn Quốc, nổi tiếng với các sản phẩm ăn vặt và đồ uống đóng chai, được phân phối độc quyền tại chuỗi cửa hàng tiện lợi GS25. Thương hiệu này được biết đến với các sản phẩm đa dạng và có bao bì bắt mắt, mang phong cách đặc trưng của Hàn Quốc.",
            "THÔNG TIN SẢN PHẨM",
            "Khối lượng tịnh: 400 g",
            "Hướng dẫn sử dụng và bảo quản:",
            "- Hướng dẫn sử dụng: Mở bao bì, dùng trực tiếp.",
            "- Bảo quản: Bảo quản trong nhiệt độ phòng, tránh ánh nắng trực tiếp và độ ẩm.",
            "NSX: Xem trên bao bì",
            "HSD: Xem trên bao bì"
        ]
    },
    {
        "id": "quat_de_ban_toc_do_cao_goojodoq_gfs007",
        "name": "Quạt để bàn tốc độ cao GOOJODOQ GFS007",
        "image": "../aff-data/quat_de_ban_toc_do_cao_goojodoq_gfs007.webp",
        "qrImage": "../aff-data/quat_de_ban_toc_do_cao_goojodoq_gfs007_qr.webp",
        "priceNow": "236.550₫",
        "priceOriginal": "400.000₫",
        "discount": "-41%",
        "buyLink": "https://s.shopee.vn/40ZF2p6wfh",
        "description": [
            "Quạt GOOJODOQ MINI & GFS007 tăng sức mạnh gió gấp 10 lần",
            "Trang bị 5 cánh turbofan góc nghiêng lớn",
            "Động cơ không chổi than tốc độ cao 20.000 RPM",
            "Tốc độ gió tối đa 9 m/s, mạnh hơn gần 10 lần quạt cầm tay thường",
            "Làm mát nhanh trong 1 giây",
            "Thiết kế bỏ túi siêu nhỏ 125 × 61 × 36 mm",
            "Trọng lượng nhẹ 151g, nhỏ hơn cả điện thoại",
            "Tay cầm thon gọn, cầm lâu không mỏi",
            "Dùng tốt cho văn phòng, trường học, du lịch, chạy bộ",
            "Hỗ trợ 100 cấp độ tốc độ gió",
            "Nhấn nhanh để tăng/giảm 20 cấp mỗi lần",
            "Nhấn giữ để điều chỉnh mượt từng cấp từ 1–100",
            "Màn hình LED hiển thị tốc độ và dung lượng pin",
            "Dây đeo tiện lợi để treo cổ khi di chuyển",
            "Dùng rảnh tay, thích hợp cho hoạt động ngoài trời",
            "Pin dung lượng 4000mAh bền bỉ",
            "Sạc đầy 2.5 giờ",
            "Thời gian sử dụng 2–12 giờ tùy tốc độ",
            "Sạc Type-C, tương thích pin sạc dự phòng, sạc ô tô, laptop"
        ]
    }
];
